version: "3"

services:
  db:
    image: postgres:13.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: umehara
      POSTGRES_PASSWORD: umehara
      POSTGRES_DB: tokai_monitor_api_dev
